config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'rooms/index'
  get 'users/profile'
  get 'users/account'
  
  devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
 }
  root to: 'home#top'

  devise_scope :user do
    get 'profile/edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile/update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  resources :rooms do
    collection do
      get 'search'
      get 'own'
    end
  end

  resources :reservations do
    collection do
      post 'confirm'
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :user_image, UserImageUploader
  validates :user_name, {presence:true}

  has_many :rooms
  has_many :reservations
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # プロフィールの編集ページ
  def profile_edit
  end
   
  #プロフィールの更新
  def profile_update
    current_user.assign_attributes(account_update_params)
    if current_user.save
      redirect_to users_profile_path 
    else
      render "profile_edit"
    end
  end

  def after_update_path_for(resource)
    users_account_path
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # プロフィールページ
  def profile
    @user = current_user
  end

  # アカウントページ
  def account
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="container UserSection">
    <h2 class="mb-4">設定</h2>
    <div class="UserContainer d-flex gap-3">
        <%= render "shared/sideber" %>
        <div class="AccountInformation w-75">
            <div class="AccountInformation__header border-bottom d-flex justify-content-between">
                <h3>アカウント</h3>
                <%= link_to edit_user_registration_path do %>
                    編集
                <% end %>
            </div>
            <div class="AccountInformation__input-group d-flex pt-3">
                <label class="w-25">メールアドレス</label>
                <p class="value w-75"><%= @user.email %></p>
            </div>
            <div class="AccountInformation__input-group d-flex pt-3">
                <label class="w-25">パスワード</label>
                <p class="value w-75">*********</p>
            </div>
        
        </div>
    </div>
</div>
<%= render "shared/footer" %>

app/views/users/profile.html.erb
<div class="container UserSection">
    <h2 class="mb-4">設定</h2>
    <div class="UserContainer d-flex gap-3">
        <%= render "shared/sideber" %>
        <div class="AccountInformation w-75">
            <div class="AccountInformation__header border-bottom d-flex justify-content-between">
                <h3>プロフィール</h3>
                <%= link_to profile_edit_path do %>
                    編集
                <% end %>
            </div>
            <div class="AccountInformation__input-group d-flex pt-3">
                <label class="w-25">アイコン画像</label>
                <p class="value w-75 mb-0">
                    <%= image_tag @user.user_image.thumb.url, class: "icon_image" %>
                </p>
            </div>
            <div class="AccountInformation__input-group d-flex pt-3">
                <label class="w-25">名前</label>
                <p class="value w-75">
                    <%= @user.user_name %>
                </p>
            </div>
            <div class="AccountInformation__input-group d-flex pt-3">
                <label class="w-25">自己紹介</label>
                <p class="value w-75">
                    <%= @user.user_introduction %>
                </p>
            </div>
        </div>
    </div>
</div>
<%= render "shared/footer" %>