config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'rooms/index'
  get 'users/profile'
  get 'users/account'
  
  devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
 }
  root to: 'home#top'

  devise_scope :user do
    get 'profile/edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile/update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  resources :rooms do
    collection do
      get 'search'
      get 'own'
    end
  end

  resources :reservations do
    collection do
      post 'confirm'
    end
  end
  
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :user
    belongs_to :room
    with_options presence: true do
        validates :check_in_date
        validates :check_out_date
        validates :user_num
    end

    #人数が1人以上となるようにする
    validates :user_num, numericality: { only_integer: true, greater_than_or_equal_to: 1}

    validate :check_in_date_cannot_be_in_the_past,
    :check_out_date_cannot_be_before_check_in_date

    #チェックイン日が本日以降の日付となるようにする 
    def check_in_date_cannot_be_in_the_past
        if check_in_date.present? && check_in_date <= Date.today
          errors.add(:check_in_date, "に過去の日付は使えません")
        end
    end

    #チェックアウト日がチェックイン日より後の日付となるようにする
    def check_out_date_cannot_be_before_check_in_date
        if check_out_date.present? && check_in_date.present? && check_out_date <= check_in_date
          errors.add(:check_out_date, "がチェックイン日より後になっていません")
        end
    end


end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # 予約一覧ページ
  def index
    @user = current_user
    @reservations = @user.reservations

  end

  # 予約確認ページ
  def confirm
    @reservation = Reservation.new(params.require(:reservation).permit(:check_in_date,:check_out_date,:user_num, :room_id))
    @reservation.user_id = current_user.id
    unless @reservation.valid?
      @room = Room.find(@reservation.room_id)
      render "rooms/show"
    end
  end

  # 予約確定
  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:check_in_date,:check_out_date,:user_num, :room_id))
    @reservation.user_id = current_user.id
    if @reservation.save
      redirect_to :reservations_index
    else
      render "confirm"
    end
  end

  # 再予約のページ
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # 予約の更新
  def update
    @reservation = Reservation.find(params[:id])
     if @reservation.update(params.require(:reservation).permit(:check_in_date,:check_out_date,:user_num))
       redirect_to :reservations
     else
       render "edit"
     end
  end

  # 予約の削除
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to :reservations_index
  end
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/reservations/confirm.html.erb
<div class="FormWrapper">
    <div class="FormContainer">
        <h2 class="mb-4">予約内容の確認</h2>
        <div class="Form ReservationConfirm">
            <div class="ReservationConfirm__value-group">
                <p class="ReservationConfirm__label">チェックイン</p>
                <p><%= @reservation.check_in_date.strftime('%Y/%m/%d') %></p>
            </div>
            <div class="ReservationConfirm__value-group">
                <p class="ReservationConfirm__label">チェックアウト</p>
                <p><%= @reservation.check_out_date.strftime('%Y/%m/%d') %></p>
            </div>
            <div class="ReservationConfirm__value-group">
                <p class="ReservationConfirm__label">日数</p>
                <% remain = (@reservation.check_out_date - @reservation.check_in_date).to_i %>
                <p><%= remain %>日</p>
            </div>
            <div class="ReservationConfirm__value-group">
                <p class="ReservationConfirm__label">人数</p>
                <p><%= @reservation.user_num %>人</p>
            </div>
            <div class="ReservationConfirm__value-group">
                <p class="ReservationConfirm__label">お支払い金額</p>
                <% totalprice = (@reservation.room.room_price * remain * @reservation.user_num) %>
                <p>¥<%= totalprice %></p>
            </div>
            <p>上記内容で正しければ「確定」ボタンを押してください。</p>
            <%= form_with model: @reservation, method: :post, url: reservations_path do |f| %>
                <%= f.hidden_field :room_id, :value => @reservation.room_id %>
                <%= f.hidden_field :check_in_date, :value => @reservation.check_in_date %>
                <%= f.hidden_field :check_out_date, :value => @reservation.check_out_date %>
                <%= f.hidden_field :user_num, :value => @reservation.user_num %>
                <div class="d-grid gap-3">
                    <%= f.submit "予約する", class:"btn btn-primary"%>
                    <%= link_to "キャンセル", @reservation.room ,class:"btn btn-outline-secondary" %>
                </div>
            <% end %>
            </div>
        </div>
    </div>
</div>
<%= render "shared/footer" %>

app/views/reservations/edit.html.erb
<div class="FormWrapper">
  <div class="FormContainer">
  <h2 class="mb-4">再予約する</h2>
    <div class="ReservationDetails">
      <%= image_tag @reservation.room.room_image.thumb.url, class:"mb-4" %>
      <div class="ReservationDetails__title d-flex justify-content-between">
        <div class="ReservationDetails__room-name fs-4">
          <%= @reservation.room.room_name %>
        </div>
        <div class="ReservationDetails__room-price Room__price fs-4">
          ¥<%= @reservation.room.room_price %>~
        </div>
      </div>
      <p class="ReservationDetails__room-address">
        <%= @reservation.room.room_address %>
      </p>
      <p class="ReservationDetails__room-content">
        <%= @reservation.room.room_introduction %>
      </p>
      <%= form_with model: @reservation do |f| %>
        <div class="ReservationsForm__input-group">
          <%= f.label :check_in_date ,"チェックイン日",class:"d-block required" %>
          <%= f.date_field :check_in_date, class:"form-control" %>
        </div>
        <div class="ReservationsForm__input-group">
          <%= f.label :check_out_date ,"チェックアウト日",class:"d-block required" %>
          <%= f.date_field :check_out_date, class:"form-control" %>
        </div>
        <div class="ReservationsForm__input-group">
          <%= f.label :user_num ,"人数",class:"d-block required" %>
          <%= f.number_field :user_num, class:"form-control" %>
        </div>
        <div class="d-grid gap-3"">
          <%= f.submit "保存" ,class:"btn btn-primary"%>
          <%= link_to :back, class:"btn btn-outline-secondary" do%>
            キャンセル
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="container ReservationsContainer">

<h3>予約済み一覧</h3>
 
 <table class="table">
   <thead>
     <tr>
       <th>画像</th>
       <th style="width: 10%">施設名</th>
       <th style="width: 40%">紹介文</th>
       <th>合計料金</th>
       <th>チェックイン</th>
       <th>チェックアウト</th>
       <th>予約確定日時</th>
     </tr>
   </thead>
 
   <tbody class="table-group-divider">
     <% @reservations.each do |reservation| %>
       <tr>
         <td><%= image_tag reservation.room.room_image.thumb130.url %></td>
         <td>
          <%= link_to reservation.room do %>
            <%= reservation.room.room_name %>
          <% end %>
        </td>
         <td><%= reservation.room.room_introduction %></td>
         <% remain = (reservation.check_out_date - reservation.check_in_date).to_i %>
         <% totalprice = (reservation.room.room_price * remain * reservation.user_num) %>
         <td>¥<%= totalprice %></td>
         <td><%= reservation.check_in_date.strftime('%Y/%m/%d') %></td>
         <td><%= reservation.check_out_date.strftime('%Y/%m/%d') %></td>
         <td><%= reservation.updated_at.strftime('%Y/%m/%d %H:%M:%S') %></td>
         <td>
          <div class="dropdown">
            <div data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-three-dots-vertical "></i>
            </div>
            <ul class="dropdown-menu">
              <li><%= link_to "再予約" , [:edit, reservation] ,class:"dropdown-item"%></li>
              <li><%= link_to "予約を削除", reservation,class:"dropdown-item", method: :delete, data: { confirm: "本当に削除しますか？" } %></li>
            </ul>
          </div>
         </td>
       </tr>
     <% end %>
   </tbody>
 </table>

 </div>