config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  get 'rooms/index'
  get 'users/profile'
  get 'users/account'
  
  devise_for :users, controllers: {
   sessions: 'users/sessions',
   registrations: 'users/registrations'
 }
  root to: 'home#top'

  devise_scope :user do
    get 'profile/edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    patch 'profile/update', to: 'users/registrations#profile_update', as: 'profile_update'
  end

  resources :rooms do
    collection do
      get 'search'
      get 'own'
    end
  end

  resources :reservations do
    collection do
      post 'confirm'
    end
  end
  
end

app/models/room.rb
class Room < ApplicationRecord
    mount_uploader :room_image, RoomImageUploader
    belongs_to :user
    has_many :reservations ,dependent: :destroy

    with_options presence: true do
        validates :room_name
        validates :room_introduction
        validates :room_price
        validates :room_address
    end

    # 料金が1円以上となるようにする
    validates :room_price, numericality: { only_integer: true, greater_than_or_equal_to: 1}
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  # 施設の新規登録ページ
  def new
    @room = Room.new
  end

  # 施設の新規登録
  def create
    @room = Room.new(params.require(:room).permit(:room_name, :room_price, :room_introduction, :room_image, :room_address))
    @room.user_id = current_user.id
    if @room.save
      redirect_to :own_rooms
    else
      render "new"
    end
  end

  # 施設の詳細ページ
  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  # 施設の編集ページ
  def edit
    @room = Room.find(params[:id])
  end

  # 施設の更新
  def update
    @room = Room.find(params[:id])
     if @room.update(params.require(:room).permit(:room_name, :room_price, :room_introduction, :room_image, :room_address))
       redirect_to :own_rooms
     else
       render "edit"
     end
  end

  #施設の削除
  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to :own_rooms
  end

  # 施設の検索結果ページ
  def search
    if params[:area].present? && params[:keyword].present?
      @rooms = Room.where('Rooms.room_address LIKE ? AND (Rooms.room_name LIKE ? OR Rooms.room_introduction LIKE ?)', "%#{params[:area]}%","%#{params[:keyword]}%","%#{params[:keyword]}%").order(created_at: :desc)
    elsif params[:area].present?
      @rooms = Room.where('Rooms.room_address LIKE ?', "%#{params[:area]}%").order(created_at: :desc)
    elsif params[:keyword].present?
      @rooms = Room.where('Rooms.room_name LIKE ? OR Rooms.room_introduction LIKE ?', "%#{params[:keyword]}%","%#{params[:keyword]}%").order(created_at: :desc)
    else
    end
  end

  # 施設の一覧ページ
  def own
    @user = current_user
    @rooms = @user.rooms
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<div class="FormWrapper">
  <div class="FormContainer">
    <h2 class="mb-4">施設情報の編集</h2>

    <%= form_with model: @room do |f| %>
      <div class="row mb-3">
        <%= f.label :room_name ,"施設名",class:"col-sm-2 col-form-label required" %>
        <div class="col-sm-10">
          <%= f.text_field :room_name,class:"form-control" %>
        </div>
      </div>
      <div class="row mb-3">
        <%= f.label :room_introduction ,"施設詳細",class:"col-sm-2 col-form-label required" %>
        <div class="col-sm-10">
          <%= f.text_area :room_introduction,class:"form-control"  %>
        </div>
      </div>
      <div class="row mb-3">
        <%= f.label :room_price ,"料金",class:"col-sm-2 col-form-label required" %>
        <div class="col-sm-10">
          <%= f.number_field :room_price,class:"form-control" %>
        </div>
      </div>
      <div class="row mb-3">
        <%= f.label :room_address ,"住所",class:"col-sm-2 col-form-label required" %>
        <div class="col-sm-10">
        <%= f.text_field :room_address,class:"form-control" %>
        </div>
      </div>
      <div class="row mb-4">
        <%= f.label :room_image ,"施設画像",class:"col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= f.file_field :room_image,class:"form-control" %>
        </div>
      </div>
    <div class="d-grid gap-3">
      <%= f.submit "保存",class:"btn btn-primary"%>
      <%= link_to :back, class:"btn btn-outline-secondary" do %>
        キャンセル
      <% end %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/rooms/new.html.erb
<div class="FormWrapper">
  <div class="FormContainer">
    <h3 class="mb-4">新規登録</h3>
    
    <%= form_with model: @room do |f| %>
      <div class="row mb-3">
        <%= f.label :room_name ,"施設名",class:"col-sm-2 col-form-label required" %>
        <div class="col-sm-10">
          <%= f.text_field :room_name,class:"form-control" %>
        </div>
      </div>
      <div class="row mb-3">
        <%= f.label :room_introduction ,"施設詳細",class:"col-sm-2 col-form-label required" %>
        <div class="col-sm-10">
          <%= f.text_area :room_introduction,class:"form-control"  %>
        </div>
      </div>
      <div class="row mb-3">
        <%= f.label :room_price ,"料金",class:"col-sm-2 col-form-label required" %>
        <div class="col-sm-10">
          <%= f.number_field :room_price,class:"form-control" %>
        </div>
      </div>
      <div class="row mb-3">
        <%= f.label :room_address ,"住所",class:"col-sm-2 col-form-label required" %>
        <div class="col-sm-10">
        <%= f.text_field :room_address,class:"form-control" %>
        </div>
      </div>
      <div class="row mb-4">
        <%= f.label :room_image ,"施設画像",class:"col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= f.file_field :room_image,class:"form-control" %>
        </div>
      </div>
    <div class="d-grid gap-3">
      <%= f.submit "登録完了する",class:"btn btn-primary"%>
      <%= link_to :back, class:"btn btn-outline-secondary" do %>
        キャンセル
      <% end %>
    </div>
    <% end %>
    <% if @room.errors.any? %>
      <div id="error_explanation" class="alert alert-danger mt-3">
        <ul>
          <% @room.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/rooms/own.html.erb
<div class="container OwnRoomsContainer">
    <h3>登録済み一覧</h3>
    <table class="table">
        <thead>
            <tr>
                <th>画像</th>
                <th>施設名</th>
                <th>紹介文</th>
                <th>料金</th>
                <th>作成日</th>
            </tr>
        </thead>

        <tbody class="table-group-divider">
            <% @rooms.each do |room| %>
                <tr>
                    <td> 
                        <%= image_tag room.room_image.thumb130.url %>
                    </td>
                    <td>
                    <%= link_to room do %>
                    <%= room.room_name %>
                    <% end %>
                    </td>
                    <td><%= room.room_introduction %></td>
                    <td>¥<%= room.room_price %>~</td>
                    <td><%= room.created_at.strftime('%Y/%m/%d') %></td>

                    <td>
                        <div class="dropdown">
                            <div data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="bi bi-three-dots-vertical "></i>
                            </div>
                            <ul class="dropdown-menu">
                            <li><%= link_to "編集", [:edit, room] ,class:"dropdown-item" %></li>
                            <li><%= link_to "削除", room, method: :delete, data: { confirm: "本当に削除しますか？" } ,class:"dropdown-item" %></li>
                            </ul>
                        </div>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>
<%= render "shared/footer" %>

app/views/rooms/search.html.erb
<%= render "shared/searchber" %>
<div class="container RoomsContainer">
    <p class="RoomsContainer__result"><span class="fw-bold lead"> <%= @rooms.count%> </span>件が見つかりました。</p>
    <ul class="RoomList d-flex flex-wrap ps-0">
        <% @rooms.each do |room| %>
            <li class="Room list-unstyled mb-5">
                <%= image_tag room.room_image.thumb437.url, class:"Room__image" %>
                <div class="RoomBodyWrapper px-3 py-5">
                    <p class="Room__name fs-4 mb-0"><%= room.room_name %></p>
                    <p class="Room__address"><%= room.room_address %></p>
                    <p class="Room__content"><%= room.room_introduction %></p>
                    <div class="RoomFooter d-flex justify-content-between">
                        <p class="Room__price fs-2">¥<%= room.room_price %>~</p>
                        <p class="Room__link"><%= link_to "詳細はこちら", room, class:"btn btn-primary p-3"%></p>
                    </div>
                </div>
            </li>
        <% end %>
    </ul>
</div>
<%= render "shared/footer" %>

app/views/rooms/show.html.erb
<%= render "shared/searchber" %>
<div class="container RoomDetailsContainer">
  <div class="RoomDetailsHeader mb-3">
    <%= link_to "←戻る", 'javascript:history.back()', class:"fs-5"%>
  </div>
  <div class="RoomDetails d-flex justify-content-between">
    <%= image_tag @room.room_image.thumb520.url, class:"Roomdetails_Room__image" %>
    <div class="RoomDetailsBody px-4 py-5">
      <div class="RoomDetailsBody__name-and-price d-flex justify-content-between">
        <p class="RoomDetails__name fs-4"><%= @room.room_name %></p>
        <p class="RoomDetails__price Room__price fs-2">¥<%= @room.room_price %>~</p>
      </div>
      <p class="RoomDetails__address"><%= @room.room_address %></p>
      <p class="RoomDetails__introduction Room__introduction"><%= @room.room_introduction %></p>

      <%= form_with model: @reservation, url: confirm_reservations_path do |f| %>
        <div class="ReservationForm__input-container d-flex p-4 gap-3">
        <%= f.hidden_field :room_id, :value => @room.id %>
          <div class="ReservationForm__input-group col-sm-4">
            <%= f.label :check_in_date ,"チェックイン",class:"d-block" %>
            <%= f.date_field :check_in_date, class:"form-control" %>
          </div>
          <div class="ReservationForm__input-group col-sm-4">
            <%= f.label :check_out_date,"チェックアウト",class:"d-block" %>
            <%= f.date_field :check_out_date, class:"form-control" %>
          </div>
          <div class="ReservationForm__input-group">
            <%= f.label :user_num ,"人数",class:"d-block" %>
            <%= f.number_field :user_num, class:"form-control" %>
          </div>
        </div>
        <div class="ReservationForm__button d-grid mt-4">
        <% if current_user %>
          <%= f.submit "予約する",class:"btn btn-primary p-3"%>
        <% else %>
          <%= link_to "ログイン",new_user_session_path, class:"btn btn-primary p-3" %>
        <% end %>
        </div>
      <% end %>

        <% if @reservation.errors.any? %>
          <div id="error_explanation" class="alert alert-danger mt-3">
            <ul>
              <% @reservation.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>